---

- name: 'audit : Ensure audit configuration directory exists'
  file:
    path: "{{ kubernetes_config_dir }}"
    owner: root
    group: root
    mode: 0755
    seuser: system_u
    serole: object_r
    setype: etc_t
    state: directory

- name: 'audit : Ensure Kube API audit configuration is installed'
  copy:
    src: audit.yml
    dest: "{{ kubernetes_audit_path }}"
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: etc_t
